// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

package account

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	db "simplebank/db/sqlc"
)

type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

type MockStoreMockRecorder struct {
	mock *MockStore
}

func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock: mock}
	return mock
}

func (mock *MockStore) EXPECT() *MockStoreMockRecorder {
	return mock.recorder
}

func (mock *MockStore) CreateAccount(ctx context.Context, arg db.CreateAccountParams) (db.Account, error) {
	mock.ctrl.T.Helper()
	results := mock.ctrl.Call(mock, "CreateAccount", ctx, arg)
	account, _ := results[0].(db.Account)
	err, _ := results[1].(error)
	return account, err
}

func (recorder *MockStoreMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	recorder.mock.ctrl.T.Helper()
	return recorder.mock.ctrl.RecordCallWithMethodType(
		recorder.mock,
		"CreateAccount",
		reflect.TypeOf((*MockStore)(nil).CreateAccount),
		ctx,
		arg,
	)
}

func (mock *MockStore) GetAccount(ctx context.Context, id int64) (db.Account, error) {
	mock.ctrl.T.Helper()
	results := mock.ctrl.Call(mock, "GetAccount", ctx, id)
	account, _ := results[0].(db.Account)
	err, _ := results[1].(error)
	return account, err
}

func (recorder *MockStoreMockRecorder) GetAccount(ctx, id any) *gomock.Call {
	recorder.mock.ctrl.T.Helper()
	return recorder.mock.ctrl.RecordCallWithMethodType(
		recorder.mock,
		"GetAccount",
		reflect.TypeOf((*MockStore)(nil).GetAccount),
		ctx,
		id,
	)
}

func (mock *MockStore) ListAccounts(ctx context.Context, arg db.ListAccountsParams) ([]db.Account, error) {
	mock.ctrl.T.Helper()
	results := mock.ctrl.Call(mock, "ListAccounts", ctx, arg)
	accounts, _ := results[0].([]db.Account)
	err, _ := results[1].(error)
	return accounts, err
}

func (recorder *MockStoreMockRecorder) ListAccounts(ctx, arg any) *gomock.Call {
	recorder.mock.ctrl.T.Helper()
	return recorder.mock.ctrl.RecordCallWithMethodType(
		recorder.mock,
		"ListAccounts",
		reflect.TypeOf((*MockStore)(nil).ListAccounts),
		ctx,
		arg,
	)
}
