name: ci-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      DB_SOURCE: postgresql://root:secret@localhost:5433/simple_bank?sslmode=disable

    services:
      postgres:
        image: postgres:18-alpine

        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank

        ports:
          - 5433:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Install migrate
        run: |
          go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.19.1
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Run migrations
        run: make migrateup

      - name: Run tests
        run: make test
